---
title: '3DViz'
author: 'Ryan Ellison'
output: 
  flexdashboard::flex_dashboard:
runtime: shiny
---
  
```{r, include = FALSE}

###Sys block
#Non-verbose warnings
options(warn = -1)

###Library block
library(plot3D)
library(RColorBrewer)
library(plotly)

###Fxn block
scatter3D_fancy <- function(x, y, z, ..., col, colvar = z){
  if (FALSE){
    'nD visualization with XY 2D mapping'
  }
  
  #Creation of 2D projection
  panelFirst <- function(pmat){
    #Project 3D object in 2D
    XY <- trans3D(x, y, z = rep(min(z), length(z)), pmat = pmat)
    
    #Create scatter plot in 2D
    scatter2D(XY$x, XY$y,
              colvar = colvar,
              colkey = FALSE,
              pch = 20,
              cex = 1,
              col = col,
              alpha = 0.75,
              add = TRUE)
  }
  
  #Create 3D projection
  scatter3D(x, y, z, ...,
            colvar = colvar,
            col = col,
            colkey = list(length = 0.5, 
                          width = 0.5, 
                          cex.clab = 0.75),
            panel.first = panelFirst)
}

pltnD <- function(regPlot, vertPlot, fancyPlot, x, y, z, c, xLab, yLab, zLab, cLab, point3D, line3D, pal, type, theta, phi){
  if (FALSE){
    'nD plotting fxn'
  }
  
  #Boolean(s) for type of 3D visualization
  if (regPlot){
    #Visualize
    scatter3D(x, y, z,
              colvar = c,
              colkey = list(length = 0.5,
                            width = 0.5,
                            cex.clab = 0.75),
              clab = cLab,
              xlab = xLab,
              ylab = yLab,
              zlab = zLab,
              bty = 'g',
              pch = 20,
              cex = point3D,
              lwd = line3D,
              col = pal,
              type = type,
              ticktype = 'detailed',
              theta = theta,
              phi = phi)  
  }
  
  if (vertPlot){
    #Visualize
    scatter3D(x, y, z,
              colvar = c,
              colkey = list(length = 0.5,
                            width = 0.5,
                            cex.clab = 0.75),
              clab = cLab,
              xlab = xLab,
              ylab = yLab,
              zlab = zLab,
              bty = 'g',
              pch = 20,
              cex = point3D,
              lwd = line3D,
              col = pal,
              type = 'h',
              ticktype = 'detailed',
              theta = theta,
              phi = phi)  
  }
  
  if (fancyPlot){
    #Visualize
    scatter3D_fancy(x, y, z,
                    colvar = c,
                    clab = cLab,
                    xlab = xLab,
                    ylab = yLab,
                    zlab = zLab,
                    bty = 'g',
                    pch = 20,
                    cex = point3D,
                    lwd = line3D,
                    col = pal,
                    type = type,
                    ticktype = 'detailed',
                    theta = theta,
                    phi = phi)
  }
}

#Global data handler
d <- reactive({
  infile <- input$data

  if (is.null(infile)){
    return(NULL)
  
  } else {
    read.csv(infile$datapath)
  }
})

```

Inputs {.sidebar data-width=325}
------------------------------------------------------
  
### __Dataset__
  
```{r}

#File input widget
fileInput(inputId = 'data',
          label = 'Select File')

#Reactivity for data slicing
output$sub <- renderUI({
  #Data dump
  data <- d()

  #If data not selected, render place holder
  if (is.null(data)){
    return(sliderInput(inputId = 'sub',
                       label = 'Subset Data',
                       min = -1,
                       max = 1,
                       step = 0.25,
                       value = c(-0.5, 0.5)))
  }
  
  #Require object to proceed
  req(data)
  
  #Slider widget
  sliderInput(inputId = 'sub',
              label = 'Subset Data',
              min = head(data[[1]], n = 1),
              max = length(data[[1]]),
              step = 1,
              value = c(head(data[[1]], n = 1), length(data[[1]])))
})

#Render slider widget
uiOutput('sub')

```

### __X Axis__

```{r}

#Reactivity for vector selection
output$x <- renderUI({
  #Data dump
  data <- d()
  
  #Select input widget
  selectInput(inputId = 'xVec',
              label = 'Vector',
              choices = names(data))
})

#Render selection widgets
uiOutput('x')

#Text input widget
textInput(inputId = 'xLab',
          label = 'Label')


```

### __Y Axis__

```{r}

#Reactivity for vector selection
output$y <- renderUI({
  #Data dump
  data <- d()
  
  #Select input widget
  selectInput(inputId = 'yVec',
              label = 'Vector',
              choices = names(data))
})

#Render selection widget
uiOutput('y')

#Text input widget
textInput(inputId = 'yLab',
          label = 'Label')

```

### __Z Axis__

```{r}

#Reactivity for vector selection
output$z <- renderUI({
  #Data dump
  data <- d()
  
  #Select input widget
  selectInput(inputId = 'zVec',
              label = 'Vector',
              choices = names(data))
})

#Render selection widget
uiOutput('z')

#Text input widget
textInput(inputId = 'zLab',
          label = 'Label')

```

### __Color Key__

```{r}

#Reactivity for vector selection
output$c <- renderUI({
  #Data dump
  data <- d()
  
  #Select input widget
  selectInput(inputId = 'cVec',
              label = 'Vector',
              choices = names(data))
})

#Render selection widget
uiOutput('c')

#Text input widget
textInput(inputId = 'cLab',
          label = 'Label')

```

### __Characteristics__

```{r}

#Radio button widget
div(style = 'display: inline-block; width: 98%; text-align: center',
    radioButtons(inputId = 'style',
                 label = 'Select Style',
                 choices = c('Points',
                             'Lines',
                             'Points + Lines'),
                 inline = TRUE))

#Reactivity for style selection
output$style <- renderUI({
  #Boolean(s) for style selection widget
  if (input$style == 'Points'){
    #Slider widget
    sliderInput(inputId = 'size', 
                label = 'Point Size',
                min = 0, 
                max = 5,
                step = 0.25,
                value = 1)
  
  } else if (input$style == 'Lines'){
    #Slider widget
    sliderInput(inputId = 'size', 
                label = 'Line Size',
                min = 0, 
                max = 5,
                step = 0.25,
                value = 1)
  
  } else {
    #Slider widget
    sliderInput(inputId = 'size', 
                label = 'Point + Line Size',
                min = 0, 
                max = 5,
                step = 0.25,
                value = 1)
  }
})

#Render slider widget
uiOutput('style')

#Selection widget
selectInput(inputId = 'col',
            label = 'Color Palette',
            choices = rownames(brewer.pal.info))

#Slider widget
sliderInput(inputId = 'horizontal', 
            label = 'Horizontal Aspect',
            min = 0, 
            max = 360,
            value = 45)

#Slider widget
sliderInput(inputId = 'vertical', 
            label = 'Vertical Aspect',
            min = 0, 
            max = 360,
            value = 40)

```

### __Save__

```{r}

#Radio button widget
div(style = 'display: inline-block; width: 98%; text-align: center',
    radioButtons(inputId = 'version',
                 label = 'Select Version',
                 choices = c('Version 1',
                             'Version 2',
                             'Version 3'),
                 inline = TRUE))

#Download button widget
div(style = 'display: inline-block; width: 98%; text-align: center',
    downloadButton(outputId = 'save',
                   label = '',
                   style = 'width: 40%'))

#Download handler
output$save <- downloadHandler(
  file = function(){paste(floor(runif(1, min = 0, max = 10^10)), '.pdf', sep = '')},
  content = function(file){
    #Data dump
    data <- d()
    
    #Create plotting device
    pdf(file)
    
    #Boolean(s) version export
    if (input$version == 'Version 1'){
      #Reactive assignment
      sizePoint <- input$size
      sizeLine <- input$size
      
      #Boolean for style selection
      if (input$style == 'Points'){
        type <- 'p'
          
      } else if (input$style == 'Lines'){
        type <- 'l'
        
      } else {
        type <- 'b'
      }
       
      #Write to device 
      pltnD(regPlot = TRUE,
            vertPlot = FALSE,
            fancyPlot = FALSE,
            data[,input$xVec][c(input$sub[1]:input$sub[2])],
            data[,input$yVec][c(input$sub[1]:input$sub[2])],
            data[,input$zVec][c(input$sub[1]:input$sub[2])],
            data[,input$cVec][c(input$sub[1]:input$sub[2])],
            input$xLab,
            input$yLab,
            input$zLab,
            input$cLab,
            sizePoint,
            sizeLine,
            c(color = colorRampPalette(brewer.pal(10, input$col))(length(data[,c(input$xVec)]))),
            type,
            input$horizontal,
            input$vertical)
    }
    
    if (input$version == 'Version 2'){
      #Reactive assignment
      sizePoint <- input$size
      sizeLine <- input$size
      
      #Write to device
      pltnD(regPlot = FALSE,
            vertPlot = TRUE,
            fancyPlot = FALSE,
            data[,input$xVec][c(input$sub[1]:input$sub[2])],
            data[,input$yVec][c(input$sub[1]:input$sub[2])],
            data[,input$zVec][c(input$sub[1]:input$sub[2])],
            data[,input$cVec][c(input$sub[1]:input$sub[2])],
            input$xLab,
            input$yLab,
            input$zLab,
            input$cLab,
            sizePoint,
            sizeLine,
            c(color = colorRampPalette(brewer.pal(10, input$col))(length(data[,c(input$xVec)]))),
            type,    
            input$horizontal,
            input$vertical)
    }
    
    if (input$version == 'Version 3'){
      #Reactive assignment
      sizePoint <- input$size
      sizeLine <- input$size
        
      #Boolean for style selection
      if (input$style == 'Points'){
        type <- 'p'
        
      } else if (input$style == 'Lines'){
        type <- 'l'
        
      } else {
        type <- 'b'
      }
      
      #Write to device
      pltnD(regPlot = FALSE,
            vertPlot = FALSE,
            fancyPlot = TRUE,
            data[,input$xVec][c(input$sub[1]:input$sub[2])],
            data[,input$yVec][c(input$sub[1]:input$sub[2])],
            data[,input$zVec][c(input$sub[1]:input$sub[2])],
            data[,input$cVec][c(input$sub[1]:input$sub[2])],
            input$xLab,
            input$yLab,
            input$zLab,
            input$cLab,
            sizePoint,
            sizeLine,
            c(color = colorRampPalette(brewer.pal(10, input$col))(length(data[,c(input$xVec)]))),
            type,  
            input$horizontal,
            input$vertical)
    }
    
    dev.off()
  }
)

```
<br/>
  
Column {data-width=225}
------------------------------------------------------
  
### Dataset
  
```{r}

#Render dataset
renderTable({
  if (is.null(d())) return(NULL)
  
  d()
})

```

Column {.tabset}
------------------------------------------------------

### Version 1
  
```{r}

#Render version 1
renderPlot({
  #Data dump
  data <- d()
  
  #Reactive assignment
  sizePoint <- input$size
  sizeLine <- input$size
  
  #Boolean for style selection
  if (input$style == 'Points'){
    type <- 'p'
    
  } else if (input$style == 'Lines'){
    type <- 'l'
    
  } else {
    type <- 'b'
  }
  
  #Return NULL if data not selected
  if (is.null(data)) return(NULL)
  
  #Require objects before proceeding
  req(data,
      input$xVec,
      input$yVec,
      input$zVec,
      input$cVec)
  
  #Visualize
  pltnD(regPlot = TRUE,
        vertPlot = FALSE,
        fancyPlot = FALSE,
        data[,input$xVec][c(input$sub[1]:input$sub[2])],
        data[,input$yVec][c(input$sub[1]:input$sub[2])],
        data[,input$zVec][c(input$sub[1]:input$sub[2])],
        data[,input$cVec][c(input$sub[1]:input$sub[2])],
        input$xLab,
        input$yLab,
        input$zLab,
        input$cLab,
        sizePoint,
        sizeLine,
        c(color = colorRampPalette(brewer.pal(10, input$col))(length(data[,c(input$xVec)]))),
        type,
        input$horizontal,
        input$vertical)
})

```

### Version 2

```{r}

#Render version 2
renderPlot({
  #Data dump
  data <- d()
  
  #Reactive assignment
  sizePoint <- input$size
  sizeLine <- input$size
  
  #Return NULL if data not selected
  if(is.null(data)) return(NULL)
  
  #Require objects before proceeding
  req(data,
      input$xVec,
      input$yVec,
      input$zVec,
      input$cVec)
  
  #Visualize
  pltnD(regPlot = FALSE,
        vertPlot = TRUE,
        fancyPlot = FALSE,
        data[,input$xVec][c(input$sub[1]:input$sub[2])],
        data[,input$yVec][c(input$sub[1]:input$sub[2])],
        data[,input$zVec][c(input$sub[1]:input$sub[2])],
        data[,input$cVec][c(input$sub[1]:input$sub[2])],
        input$xLab,
        input$yLab,
        input$zLab,
        input$cLab,
        sizePoint,
        sizeLine,
        c(color = colorRampPalette(brewer.pal(10, input$col))(length(data[,c(input$xVec)]))),
        type,    
        input$horizontal,
        input$vertical)
})

```

### Version 3

```{r}

#Render version 3
renderPlot({
  #Data dump
  data <- d()
  
  #Reactive assignment
  sizePoint <- input$size
  sizeLine <- input$size
  
  #Boolean for style selection
  if (input$style == 'Points'){
    type <- 'p'

  } else if (input$style == 'Lines'){
    type <- 'l'
    
  } else {
    type <- 'b'
  }
  
  #Return NULL if data not selected
  if (is.null(data)) return(NULL)
  
  #Require objects before proceeding
  req(data,
      input$xVec,
      input$yVec,
      input$zVec,
      input$cVec)
  
  #Visualize
  pltnD(regPlot = FALSE,
        vertPlot = FALSE,
        fancyPlot = TRUE,
        data[,input$xVec][c(input$sub[1]:input$sub[2])],
        data[,input$yVec][c(input$sub[1]:input$sub[2])],
        data[,input$zVec][c(input$sub[1]:input$sub[2])],
        data[,input$cVec][c(input$sub[1]:input$sub[2])],
        input$xLab,
        input$yLab,
        input$zLab,
        input$cLab,
        sizePoint,
        sizeLine,
        c(color = colorRampPalette(brewer.pal(10, input$col))(length(data[,c(input$xVec)]))),
        type,  
        input$horizontal,
        input$vertical)
})

```

